# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 23:09
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VMR', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commuteflow',
            name='line',
            field=django.contrib.gis.db.models.fields.LineStringField(srid=4326),
        ),
    ]
