# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 16:08
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VMR', '0002_auto_20170325_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='MegaRegion',
            fields=[
                ('center', models.IntegerField(primary_key=True, serialize=False, verbose_name='10 Digit MegaRegion Center FIPS Code')),
                ('name', models.CharField(max_length=50)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
